//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcpayOrders
    {
        public string MerchantTradeNo { get; set; }
        public string MemberID { get; set; }
        public Nullable<int> RtnCode { get; set; }
        public string RtnMsg { get; set; }
        public string TradeNo { get; set; }
        public Nullable<int> TradeAmt { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentType { get; set; }
        public string PaymentTypeChargeFee { get; set; }
        public string TradeDate { get; set; }
        public Nullable<int> SimulatePaid { get; set; }
    }
}
