//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day07.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class tEmployee
    {
        [DisplayName("員工名稱")]
        [Required]
        public string fName { get; set; }
        
        [DisplayName("員工薪水")]
        [Range(22000,50000, ErrorMessage = "22000~50000")]
        [Required]
        public Nullable<int> fSalary { get; set; }

        [DisplayName("員工手機")]
        [RegularExpression("^09[0-9]{8}$",ErrorMessage ="手機輸入有誤")]
        [Required]
        public string fPhone { get; set; }

        [DisplayName("員工信箱")]
        [EmailAddress]
        [Required]
        public string fEmail { get; set; }

        [DisplayName("員工編號")]
        [StringLength(5, ErrorMessage = "至少5個字元", MinimumLength = 5)]
        [Required]
        public string fEmpId { get; set; }
        public int fId { get; set; }

        [DisplayName("員工日期")]
        [Required]
        public string fDate { get; set; }
    }
}
