//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 產品資料
    {
        public string 產品編號 { get; set; }
        public string 品名 { get; set; }
        public Nullable<int> 單價 { get; set; }
        public string 圖示 { get; set; }
        public Nullable<int> 類別編號 { get; set; }
        public string 編輯者 { get; set; }
        public string 建立日 { get; set; }
        public string 修改日 { get; set; }
    }
}
